<%
  secured_settings_file_path = Rails.root.to_s + "/config/settings/secured_settings.yml"
  if File.exists?(secured_settings_file_path)
%>
  <%= ERB.new(IO.read(secured_settings_file_path)).result %>
<%end%>

default_host: "localhost:3000"



